name: lighthouse

on: [deployment_status]

jobs:
  lighthouse:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.creator.login == 'deno-deploy[bot]'
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github) }}" 